### ISSUE TITLE
Link to PCB page is broken

### ISSUE THREAD

**Issue by beeb** [m1geo/MAX6921_VFD_GPS_Clock#1]
Hello and thanks for this great open-source project! The link to the PCB manufacturer is broken. Would i be possible to get the files for the custom driver PCB?

**Comment by m1geo** [comment]
Sure, I'll take a look at this in a few moments.On 4 Jan 2017 10:30, Valentin Bersier <notifications@github.com> wrote:Hello and thanks for this great open-source project! The link to the PCB manufacturer is broken. Would i be possible to get the files for the custom driver PCB?

**Comment by beeb** [comment]
Wonderful, I also posted a few questions as comment on the YouTube video, we can move the discussion on github if you prefer. Thanks!

**Comment by m1geo** [comment]
#bfc1906 fixed the issue with the PCB link. Thanks.

**Comment by beeb** [comment]
Thanks for looking into this. Unfortunately, when I click on the new link, the site redirects me to the page http://dirtypcbs.com/store/designer and their search function does not work, so I'm unable to find it myself.

Best,
Val

**EDIT:** After scrolling though the 45 pages I got it:
http://dirtypcbs.com/store/designer/details/George+M1GEO/783/m1geo-iv-11-vfd-boards is the correct link

**Comment by m1geo** [comment]
Yes, that is the correct link. After updating the URL, I edited my username, which broke the URL again! I'm very sorry. That is the correct link! Enjoy building the clock
